# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclude generated files and build folders
  exclude:
    - build/**
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
  
  # Enable stricter type checking
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  # Treat warnings as errors in CI/CD
  errors:
    # Make certain lints errors instead of warnings
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error

linter:
  rules:
    # Code style and formatting
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    
    # Performance and efficiency
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    avoid_function_literals_in_foreach_calls: true
    prefer_spread_collections: true
    prefer_collection_literals: true
    
    # Error handling and safety
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    avoid_null_checks_in_equality_operators: true
    avoid_catching_errors: true
    use_rethrow_when_possible: true
    
    # Documentation and naming
    public_member_api_docs: false # Set to true for production
    lines_longer_than_80_chars: false # Set to true for strict formatting
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    
    # Code style (informational)
    cascade_invocations: false
    parameter_assignments: false
    unawaited_futures: false
    
    # Flutter specific
    use_build_context_synchronously: true
    avoid_web_libraries_in_flutter: true
    prefer_relative_imports: true
    
    # Security and privacy
    avoid_print: true # Use debugPrint instead
    
    # Null safety
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    avoid_redundant_argument_values: true
    
    # Additional code quality rules
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_renaming_method_parameters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: false
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    depend_on_referenced_packages: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_private_types_in_public_api: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_default_cases: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: false
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    require_trailing_commas: true
    secure_pubspec_urls: true
    sort_constructors_first: true
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unreachable_from_main: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
