// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCspFbHlUpTMAnASOZPVtv6YR2WnoN-UGc',
    appId: '1:469574372868:web:241930d76d05d1ce702f51',
    messagingSenderId: '469574372868',
    projectId: 'runes-78794',
    authDomain: 'runes-78794.firebaseapp.com',
    storageBucket: 'runes-78794.firebasestorage.app',
    measurementId: 'G-229NVP2911',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDET4Dfq__upJo0xmJhRpnHdBrtCw0tG5o',
    appId: '1:469574372868:android:5a57ab027ab4f797702f51',
    messagingSenderId: '469574372868',
    projectId: 'runes-78794',
    storageBucket: 'runes-78794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFch_btpaLxTj2i3NzfdrULx6mm0V8iOg',
    appId: '1:469574372868:ios:58920204ec5e020a702f51',
    messagingSenderId: '469574372868',
    projectId: 'runes-78794',
    storageBucket: 'runes-78794.firebasestorage.app',
    androidClientId: '469574372868-qttmierun3lojm19lhn93q4jui3vstpk.apps.googleusercontent.com',
    iosClientId: '469574372868-en4en0bi3nn5fock9f434auuq27ns39a.apps.googleusercontent.com',
    iosBundleId: 'com.example.runes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFch_btpaLxTj2i3NzfdrULx6mm0V8iOg',
    appId: '1:469574372868:ios:58920204ec5e020a702f51',
    messagingSenderId: '469574372868',
    projectId: 'runes-78794',
    storageBucket: 'runes-78794.firebasestorage.app',
    androidClientId: '469574372868-qttmierun3lojm19lhn93q4jui3vstpk.apps.googleusercontent.com',
    iosClientId: '469574372868-en4en0bi3nn5fock9f434auuq27ns39a.apps.googleusercontent.com',
    iosBundleId: 'com.example.runes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCspFbHlUpTMAnASOZPVtv6YR2WnoN-UGc',
    appId: '1:469574372868:web:3fd2be74a9ed4133702f51',
    messagingSenderId: '469574372868',
    projectId: 'runes-78794',
    authDomain: 'runes-78794.firebaseapp.com',
    storageBucket: 'runes-78794.firebasestorage.app',
    measurementId: 'G-ES19VH86VN',
  );
}
